[package]
edition = "2021"
license = "MIT"
name    = "zed_psalm"
publish = false
version = "0.0.1"

[lib]
crate-type = ["cdylib"]
path       = "src/psalm.rs"

[dependencies]
zed_extension_api = "0.7.0"
