authors        = ["Peter"]
description    = "Zed extension for Psalm, a static analysis tool for PHP"
id             = "psalm"
name           = "Psalm"
repository     = "https://github.com/peterjbassi/psalm-zed"
schema_version = 1
version        = "0.0.2"

[language_servers.psalm]
languages         = ["PHP"]
